import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
const orbitron = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Santino Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={orbitron.className}>
      <body>{children}</body>
    </html>
  );
}
